#language: python
#matrix:
#  include:
#    - env: CONFIG="Python3.5"
#      os: linux
#      python: 3.5
#      before_install:
##        - sudo apt-get -qq update
##        - GRC_VERSION="$(curl -s https://api.github.com/repos/garabik/grc/releases/latest | grep 'tag_name' | cut -d : -f 2 | tr -d \, | tr -d \" | cut -c3-)"
#        - GRC_VERSION=1.11.3
#        - GRC_FILE="grc_${GRC_VERSION}-1_all.deb"
#        - curl -L https://korpus.sk/~garabik/software/grc/$GRC_FILE -o grc.deb
#        - FORCE="$([ "$(command -v python3)" != "/usr/bin/python3" ] && echo "--ignore-depends=python3:any")"
#        - echo $FORCE
#        - sudo dpkg --ignore-depends=python3:any -i grc.deb
#    - env: CONFIG="Python3.6"
#      os: linux
#      python: 3.6
#      before_install:
##        - sudo apt-get -qq update
#        - GRC_VERSION="$(curl -s https://api.github.com/repos/garabik/grc/releases/latest | grep 'tag_name' | cut -d : -f 2 | tr -d \, | tr -d \" | cut -c3-)"
#        - GRC_FILE="grc_${GRC_VERSION}-1_all.deb"
#        - curl -L https://korpus.sk/~garabik/software/grc/$GRC_FILE -o grc.deb
#        - FORCE="$([ "$(command -v python3)" != "/usr/bin/python3" ] && echo "--ignore-depends=python3:any")"
#        - sudo dpkg $FORCE -i grc.deb
#addons:
#  apt:
#    update: true
#install:
#  - pip3 install -r tools/Travis-CI/requirements.txt
#before_script:
#  - ./tools/Travis-CI/pyIPCMI.setup.sh
#script:
#  - ./tools/Travis-CI/pyIPCMI.dryrun.sh



language: python

install: skip

if: tag IS present

script:
  - echo "No tests. Just deploying to PyPI."

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
